version: "3.8"

services:
  dev:
    dockerfile: Dockerfile
    # image: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
    command: sleep infinity
    volumes:
      - ..:/workspaces:cached
      - .:/workspace
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "P@ssw0rdStrong!"
      ACCEPT_EULA: "Y"
      
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
      # - .devcontainer:/workspace/.devcontainer:ro
    command: 
      "/opt/mssql/bin/sqlservr"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'P@ssw0rdStrong!' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mssqldata:
