version: "3.9"

services:
  dotnet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-app
    depends_on:
      - mssql
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      # Example connection string for your app
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=AppDb;User Id=sa;Password=P@ssw0rdStrong!;TrustServerCertificate=True;"
    ports:
      - "5000:5000"
      - "5001:5001"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rdStrong!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rdStrong!' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  mssql_data:
