version: "3.9"

services:
  dev:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    depends_on:
      - mssql
    volumes:
      - ..:/workspaces:cached:ro
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=master;User Id=SA;Password=P@ssw0rdStrong!;TrustServerCertificate=True;"
    ports:
      - "5000:5000"
      - "5001:5001"
    # command: bash -c "apt -y update && apt install -y curl apt-transport-https ca-certificates unixodbc-dev"
    # command: bash -c "apt-get update && DEBIAN_FRONTEND=noninteractive && apt-get install -y curl gnupg apt-transport-https ca-certificates unixodbc-dev && rm -rf /var/lib/apt/lists/*"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rdStrong!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'P@ssw0rdStrong!' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  mssql_data:
