version: "3.8"

services:
  dev:
    image: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
    command: sleep infinity
    volumes:
      - ..:/workspaces:cached
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "P@ssw0rdStrong!"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
