version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-dotnet-mssql
    ports:
      - "1433:1433"     # SQL Server
      - "5000:5000"     # Optional: your app HTTP
      - "5001:5001"     # Optional: your app HTTPS
    environment:
      # --- Required by SQL Server container ---
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rdStrong!"   # change me (meets complexity)
      MSSQL_PID: "Developer"               # or Express / Evaluation
      # --- Common optional MSSQL settings ---
      MSSQL_AGENT_ENABLED: "true"          # enable SQL Agent if needed
      # MSSQL_COLLATION: "SQL_Latin1_General_CP1_CI_AS"
      # MSSQL_BACKUP_DIR: "/var/opt/mssql/backup"
      # MSSQL_DATA_DIR:   "/var/opt/mssql/data"
      # MSSQL_LOG_DIR:    "/var/opt/mssql/log"
      # MSSQL_DUMP_DIR:   "/var/opt/mssql/dump"
    volumes:
      - mssql_data:/var/opt/mssql      # persist DB data between rebuilds
      - .:/workspace                   # your source code
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P \"P@ssw0rdStrong!\" -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    stdin_open: true
    tty: true
    command: /opt/mssql/bin/sqlservr  # start SQL Server (default entrypoint supports envs)

volumes:
  mssql_data:

